# Generated by Django 5.2.10 on 2026-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0003_dispatcherbooked_all_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherbooked',
            name='date',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
