# Generated by Django 5.2.10 on 2026-04-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0008_alter_dispatcherbooked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherbooked',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
