# Generated by Django 5.2.10 on 2026-04-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0010_alter_dispatcherbooked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcherbooked',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
