# Generated by Django 5.2.10 on 2026-04-13 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0011_dispatcherbooked_viewed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatcherbooked',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='dispatcherbooked',
            name='viewed_at',
        ),
        migrations.AlterModelTable(
            name='dispatcherbooked',
            table='dispatcher_booked',
        ),
        migrations.CreateModel(
            name='DispatcherBookedSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('dispatcher_booked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seen_records', to='dispatcher_booked.dispatcherbooked')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_dispatcher_booked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispatcher_booked_user_seen',
                'unique_together': {('user', 'dispatcher_booked')},
            },
        ),
    ]
