# Generated by Django 5.2.10 on 2026-04-13 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0012_alter_dispatcherbooked_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherbooked',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
