# Generated by Django 5.2.10 on 2026-04-13 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0013_alter_dispatcherbooked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherbooked',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
