# Generated by Django 5.2.10 on 2026-04-11 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the service', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the service', null=True)),
                ('category', models.CharField(choices=[('scraper', 'Scraper'), ('api', 'API Endpoint'), ('database', 'Database'), ('external', 'External Service')], help_text='Service category', max_length=50)),
                ('current_status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded Performance'), ('partial_outage', 'Partial Outage'), ('major_outage', 'Major Outage')], default='operational', help_text='Current operational status', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this service is being monitored')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display on status page')),
                ('check_type', models.CharField(default='auto', help_text='Type of health check (auto, manual)', max_length=50)),
                ('freshness_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes of no activity before flagging as degraded')),
                ('outage_threshold_minutes', models.PositiveIntegerField(default=60, help_text='Minutes of no activity before flagging as outage')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='Last time this service was checked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monitored Service',
                'verbose_name_plural': 'Monitored Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(help_text="Identifier matching the Service slug (e.g., 'dispatcher-booked-scraper')", max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error traceback if failed', null=True)),
                ('records_processed', models.PositiveIntegerField(default=0, help_text='Number of records successfully processed/inserted')),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Total execution time in seconds', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional execution context (e.g., counts, URLs visited)', null=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Scraper Execution Log',
                'verbose_name_plural': 'Scraper Execution Logs',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['scraper_name', '-executed_at'], name='status_scra_scraper_a9ef13_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the incident', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the issue', null=True)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='major', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the incident started')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When someone acknowledged it', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the service recovered', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Total downtime in seconds', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the incident has been resolved')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Whether someone has acknowledged it')),
                ('alert_sent', models.BooleanField(default=False, help_text='Whether downtime alert email was sent')),
                ('recovery_sent', models.BooleanField(default=False, help_text='Whether recovery email was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(help_text='The affected service', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='status.service')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['service', '-started_at'], name='status_inci_service_c37262_idx'), models.Index(fields=['is_resolved', '-started_at'], name='status_inci_is_reso_15a519_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], help_text='Result of the check', max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if check failed', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional check details (e.g., last record timestamp)', null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this check was performed')),
                ('service', models.ForeignKey(help_text='The service that was checked', on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='status.service')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Checks',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['service', '-checked_at'], name='status_heal_service_9f8b0c_idx'), models.Index(fields=['-checked_at'], name='status_heal_checked_26c1f1_idx')],
            },
        ),
    ]
