# Generated by Django 5.2.10 on 2026-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='service',
        ),
        migrations.AlterField(
            model_name='scraperexecutionlog',
            name='scraper_name',
            field=models.CharField(help_text="Identifier matching the Service (e.g., 'dispatcher-booked-scraper')", max_length=255),
        ),
        migrations.DeleteModel(
            name='HealthCheck',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
