# Generated by Django 5.2.10 on 2026-04-11 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_incident_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('is_operational', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('outage_started_at', models.DateTimeField(blank=True, null=True)),
                ('tracked_since', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_downtime_seconds', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
