# Generated by Django 5.2.10 on 2026-04-13 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_servicestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='The scraper or service name (e.g. dispatcher-booked-scraper)', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Error description or traceback')),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_description', models.TextField(blank=True, help_text='Auto added description when resolved', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
