# Generated by Django 5.2.10 on 2026-04-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatus',
            name='last_outage_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last outage email was sent. Prevents duplicate alerts.', null=True),
        ),
    ]
