# Generated by Django 5.2.10 on 2026-01-20 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('priority_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tech_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.CharField(blank=True, max_length=50, null=True)),
                ('call_type', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('EMERGENCY', 'Emergency'), (None, 'None')], max_length=20, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('called_by', models.CharField(blank=True, max_length=100, null=True)),
                ('called_by_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('locates_called', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_remaining', models.CharField(blank=True, max_length=50, null=True)),
                ('timer_started', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locate',
                'verbose_name_plural': 'Locates',
                'db_table': 'locates_dashboard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='Date the work is scheduled', null=True)),
                ('elapsed_time', models.DateTimeField(blank=True, help_text='Time elapsed as a string', max_length=50, null=True)),
                ('technician', models.CharField(blank=True, help_text='Name or ID of the technician', max_length=255, null=True)),
                ('wo_number', models.CharField(blank=True, help_text='Work Order Number', max_length=100, null=True)),
                ('full_address', models.TextField(blank=True, help_text='Full address of the location', null=True)),
                ('last_report_link', models.URLField(blank=True, help_text='Link to the last report', max_length=500, null=True)),
                ('unlocked_report_link', models.URLField(blank=True, help_text='Link to the unlocked report', max_length=500, null=True)),
                ('tech_report_submitted', models.BooleanField(blank=True, default=False, help_text='Has the technician report been submitted?', null=True)),
                ('status', models.CharField(blank=True, help_text='Current status of the work order', max_length=50, null=True)),
                ('wait_to_lock', models.BooleanField(blank=True, default=False, help_text='Flag to wait before locking', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the status or action', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('moved_to_holding_date', models.DateTimeField(blank=True, help_text='Date when moved to holding', null=True)),
                ('moved_created_by', models.CharField(blank=True, help_text='User who moved it to holding', max_length=255, null=True)),
                ('deleted_by', models.CharField(blank=True, help_text='User who deleted the record', max_length=255, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, help_text='Email of the user who deleted the record', max_length=255, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, help_text='Date of deletion', null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, help_text='Soft delete flag', null=True)),
                ('rme_completed', models.BooleanField(blank=True, default=False, help_text='Is RME completed?', null=True)),
                ('finalized_by', models.CharField(blank=True, help_text='User who finalized the order', max_length=255, null=True)),
                ('finalized_by_email', models.EmailField(blank=True, help_text='Email of the user who finalized', max_length=255, null=True)),
                ('finalized_date', models.DateTimeField(blank=True, help_text='Date of finalization', null=True)),
                ('report_id', models.CharField(blank=True, help_text='Associated Report ID', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
