# Generated by Django 5.2.10 on 2026-01-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workordertoday',
            options={'ordering': ['-elapsed_time'], 'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.AddField(
            model_name='locates',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Indicates if this locate record has been seen'),
        ),
        migrations.AddField(
            model_name='workordertoday',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Indicates if this work order has been seen'),
        ),
    ]
