# Generated by Django 5.2.10 on 2026-01-25 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0002_alter_workordertoday_options_locates_is_seen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordertoday',
            name='is_seen',
        ),
        migrations.CreateModel(
            name='LocateSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('locate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='locates.locates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'locate'], name='locates_loc_user_id_f682fd_idx')],
                'unique_together': {('user', 'locate')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='locates.workordertoday')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'work_order'], name='locates_wor_user_id_c0327b_idx')],
                'unique_together': {('user', 'work_order')},
            },
        ),
    ]
