# Generated by Django 5.2.10 on 2026-01-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0003_remove_workordertoday_is_seen_locateseen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locates',
            name='is_seen',
        ),
    ]
