# Generated by Django 5.2.10 on 2026-01-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0004_remove_locates_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderTodayEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_order_today', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_data', to='locates.workordertoday')),
            ],
            options={
                'verbose_name': 'Work Order Today Edit',
                'verbose_name_plural': 'Work Order Edits',
                'ordering': ['-id'],
            },
        ),
    ]
