# Generated by Django 5.2.10 on 2026-02-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0005_workordertodayedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertodayedit',
            name='septic_components_form_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
