# Generated by Django 5.2.10 on 2026-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0006_workordertodayedit_septic_components_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertoday',
            name='elapsed_time_rme_completed',
            field=models.DateTimeField(blank=True, help_text='RME Completed Time elapsed as a string', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workordertoday',
            name='task_name',
            field=models.CharField(blank=True, help_text='Current task of the work order', max_length=100, null=True),
        ),
    ]
