# Generated by Django 5.2.10 on 2026-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0007_workordertoday_elapsed_time_rme_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertoday',
            name='completed_date',
            field=models.DateTimeField(blank=True, help_text='Date the work is scheduled', null=True),
        ),
    ]
