# Generated by Django 5.2.10 on 2026-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0008_workordertoday_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertoday',
            name='completed_date',
            field=models.CharField(blank=True, help_text='Date the work is Completed', max_length=100, null=True),
        ),
    ]
