# Generated by Django 5.2.10 on 2026-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0009_alter_workordertoday_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertoday',
            name='customer',
            field=models.CharField(blank=True, help_text='Customer name', max_length=255, null=True),
        ),
    ]
