# Generated by Django 5.2.10 on 2026-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0012_workordertoday_completed_elapsed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='locates',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locates',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
