# Generated by Django 5.2.10 on 2026-05-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0013_locates_error_type_locates_is_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertoday',
            name='wo_details_link',
            field=models.URLField(blank=True, help_text='Direct link to the work order details', max_length=1000, null=True),
        ),
    ]
