# Generated by Django 5.2.10 on 2026-05-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0014_workordertoday_wo_details_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordertoday',
            name='task_name',
        ),
        migrations.AddField(
            model_name='workordertoday',
            name='priority_name',
            field=models.CharField(blank=True, help_text='Priority of the work order', max_length=100, null=True),
        ),
    ]
