# Generated by Django 5.2.10 on 2026-04-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cameron_booked', models.PositiveIntegerField(blank=True, null=True)),
                ('cameron_total', models.PositiveIntegerField(blank=True, null=True)),
                ('eric_booked', models.PositiveIntegerField(blank=True, null=True)),
                ('eric_total', models.PositiveIntegerField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
