# Generated by Django 5.2.10 on 2026-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcherbooked',
            name='total_jobs_booked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
