# Generated by Django 5.2.10 on 2026-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0002_dispatcherbooked_total_jobs_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcherbooked',
            name='all_leads',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
