# Generated by Django 5.2.10 on 2026-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_booked', '0004_alter_dispatcherbooked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcherbooked',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
