# Generated by Django 5.2.10 on 2026-04-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_employee_review_employees_mentioned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='employees_mentioned',
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_by',
            field=models.CharField(blank=True, help_text='User who deleted the record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_by_email',
            field=models.EmailField(blank=True, help_text='Email of the user who deleted the record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_date',
            field=models.DateTimeField(blank=True, help_text='Date of deletion', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, help_text='Soft delete flag', null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
