# Generated by Django 5.2.10 on 2026-04-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviewseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_name',
            field=models.CharField(default='Google - Sterling Septic & Plumbing LLC', max_length=255),
        ),
    ]
