# Generated by Django 5.2.10 on 2026-03-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='submittedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
