# Generated by Django 5.2.10 on 2026-03-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0002_workorder_completedat_workorder_submittedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='wo',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
