# Generated by Django 5.2.10 on 2026-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0010_workordertoday_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertoday',
            name='scheduled_date',
            field=models.CharField(blank=True, help_text='Date the work is scheduled', max_length=100, null=True),
        ),
    ]
