# Generated by Django 5.2.10 on 2026-03-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locates', '0011_alter_workordertoday_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordertoday',
            name='completed_elapsed_time',
            field=models.CharField(blank=True, help_text='Date the work is Completed and Elapsed Time', max_length=100, null=True),
        ),
    ]
