# Generated by Django 5.2.10 on 2026-05-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marked_travel_start', models.TimeField(blank=True, null=True)),
                ('marked_travel_end', models.TimeField(blank=True, null=True)),
                ('marked_travel_duration', models.IntegerField(default=0, help_text='Duration in minutes (Variant)')),
                ('actual_travel_start', models.TimeField(blank=True, null=True)),
                ('actual_travel_end', models.TimeField(blank=True, null=True)),
                ('actual_travel_duration', models.IntegerField(default=0, help_text='Duration in minutes (Standard)')),
                ('travel_coding_proficiency', models.FloatField(default=0.0, help_text='Travel Coding Proficiency (%)')),
                ('marked_worked_start', models.TimeField(blank=True, null=True)),
                ('marked_worked_end', models.TimeField(blank=True, null=True)),
                ('marked_worked_duration', models.IntegerField(default=0, help_text='Duration in minutes (Variant)')),
                ('actual_worked_start', models.TimeField(blank=True, null=True)),
                ('actual_worked_end', models.TimeField(blank=True, null=True)),
                ('actual_worked_duration', models.IntegerField(default=0, help_text='Duration in minutes (Standard)')),
                ('time_tracking_proficiency', models.FloatField(default=0.0, help_text='Time Tracking Proficiency (%)')),
                ('time_billed_duration', models.IntegerField(default=0, help_text='Time Billed in minutes (Variant)')),
                ('billing_proficiency', models.FloatField(default=0.0, help_text='Billing Proficiency (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_tracking',
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
