# Generated by Django 5.2.10 on 2026-05-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetracking',
            options={'ordering': ['-date', 'technician_name']},
        ),
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='technician_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='wo_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
