# Generated by Django 5.2.10 on 2026-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_alter_timetracking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_idle_duration',
            field=models.IntegerField(default=0, help_text='Idle Duration in minutes'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_stop_duration',
            field=models.IntegerField(default=0, help_text='Stop Duration in minutes'),
        ),
    ]
