# Generated by Django 5.2.10 on 2026-05-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_timetracking_fleetmatics_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
