# Generated by Django 5.2.10 on 2026-05-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0004_timetracking_latitude_timetracking_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='actual_travel_duration',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='actual_travel_end',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='actual_travel_start',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='marked_travel_duration',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='marked_travel_end',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='marked_travel_start',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='marked_worked_duration',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='marked_worked_end',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='marked_worked_start',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='travel_coding_proficiency',
        ),
    ]
