# Generated by Django 5.2.10 on 2026-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0005_remove_timetracking_actual_travel_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='activity_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_moving_duration',
            field=models.IntegerField(default=0, help_text='Moving Duration in minutes'),
        ),
    ]
