# Generated by Django 5.2.10 on 2026-05-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0006_timetracking_activity_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='billing_proficiency',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='time_billed_duration',
        ),
    ]
