# Generated by Django 5.2.10 on 2026-05-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0007_remove_timetracking_billing_proficiency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='time_tracking_proficiency',
        ),
    ]
