# Generated by Django 5.2.10 on 2026-05-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0008_remove_timetracking_time_tracking_proficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetracking',
            old_name='actual_worked_duration',
            new_name='fieldedge_worked_duration',
        ),
        migrations.RenameField(
            model_name='timetracking',
            old_name='actual_worked_end',
            new_name='fieldedge_worked_end',
        ),
        migrations.RenameField(
            model_name='timetracking',
            old_name='actual_worked_start',
            new_name='fieldedge_worked_start',
        ),
    ]
