# Generated by Django 5.2.10 on 2026-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0009_rename_actual_worked_duration_timetracking_fieldedge_worked_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='fieldedge_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
