# Generated by Django 5.2.10 on 2026-05-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0010_timetracking_fieldedge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='fieldedge_status',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fieldedge_worked_duration',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fieldedge_worked_end',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fieldedge_worked_start',
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fieldedge_data',
            field=models.JSONField(blank=True, default=list, help_text='List of activities from FieldEdge', null=True),
        ),
    ]
