# Generated by Django 5.2.10 on 2026-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0011_remove_timetracking_fieldedge_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='activity_category',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fleetmatics_address',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fleetmatics_arrival_time',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fleetmatics_departure_time',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fleetmatics_idle_duration',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fleetmatics_moving_duration',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='fleetmatics_stop_duration',
        ),
        migrations.AddField(
            model_name='timetracking',
            name='fleetmatics_data',
            field=models.JSONField(blank=True, default=list, help_text='List of matching activities from Fleetmatics', null=True),
        ),
    ]
