# Generated by Django 5.2.10 on 2026-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0012_remove_timetracking_activity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
