# Generated by Django 5.2.10 on 2026-05-06 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0014_timetracking_deleted_at_timetracking_deleted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTrackingSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seen_records', to='time_tracking.timetracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_time_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'time_tracking_user_seen',
                'unique_together': {('user', 'record')},
            },
        ),
    ]
