# Generated by Django 5.2.10 on 2026-05-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0015_timetrackingseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='user',
        ),
    ]
