# Generated by Django 5.2.10 on 2026-05-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0016_remove_timetracking_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetracking',
            unique_together={('wo_number', 'date')},
        ),
    ]
