# Generated by Django 5.2.10 on 2026-03-17 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.JSONField(blank=True, default=list, help_text='List of tags', null=True)),
                ('customerName', models.CharField(blank=True, max_length=255, null=True)),
                ('workOrderAddress', models.TextField(blank=True, null=True)),
                ('workOrderSummary', models.TextField(blank=True, null=True)),
                ('workOrderLink', models.URLField(blank=True, max_length=500, null=True)),
                ('quoteLink', models.URLField(blank=True, max_length=500, null=True)),
                ('technicianName', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('wo', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('completedNote', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('viewedAt', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'work_orders',
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_work_orders', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seen_records', to='work_order.workorder')),
            ],
            options={
                'db_table': 'work_order_user_seen',
                'unique_together': {('user', 'work_order')},
            },
        ),
    ]
