# Generated by Django 5.2.10 on 2026-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0003_alter_workorder_wo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
