# Generated by Django 5.2.10 on 2026-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
