# Generated by Django 5.2.10 on 2026-04-08 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='quoteLink',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workOrderLink',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
