# Generated by Django 5.2.10 on 2026-04-23 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=100, unique=True)),
                ('technician_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('assignment_completed', models.BooleanField(default=False)),
                ('worked_time_hours', models.FloatField(default=0.0, help_text='Time worked in decimal hours')),
                ('invoiced_time_hours', models.FloatField(default=0.0, help_text='Total worth of invoiced items in hours')),
                ('proficiency_percentage', models.FloatField(default=0.0, help_text='Invoiced Time / Worked Time * 100')),
                ('total_amount', models.FloatField(default=0.0, help_text='Invoice Total')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('items_detail', models.JSONField(blank=True, default=list, help_text='Item numbers, quantities, and worth values')),
                ('work_order_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_proficiency',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProficiencySeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_proficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seen_records', to='invoice_proficiency.invoiceproficiency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_invoice_proficiency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_proficiency_user_seen',
                'unique_together': {('user', 'invoice_proficiency')},
            },
        ),
    ]
