# Generated by Django 5.2.10 on 2026-05-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceproficiency',
            old_name='work_order_summary',
            new_name='wo_summary',
        ),
    ]
