# Generated by Django 5.2.10 on 2026-04-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproficiency',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
