# Generated by Django 5.2.10 on 2026-04-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0002_invoiceproficiency_invoice_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceproficiency',
            options={'ordering': ['-work_order_date', '-id']},
        ),
        migrations.RenameField(
            model_name='invoiceproficiency',
            old_name='date',
            new_name='work_order_date',
        ),
    ]
