# Generated by Django 5.2.10 on 2026-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0002_rename_work_order_summary_invoiceproficiency_wo_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproficiency',
            name='assignment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
