# Generated by Django 5.2.10 on 2026-05-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0003_invoiceproficiency_assignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproficiency',
            name='assignment_status',
        ),
    ]
