# Generated by Django 5.2.10 on 2026-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0003_alter_invoiceproficiency_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproficiency',
            name='error_description',
            field=models.TextField(blank=True, help_text='Why this record is marked as invalid', null=True),
        ),
        migrations.AddField(
            model_name='invoiceproficiency',
            name='is_invalid',
            field=models.BooleanField(default=False, help_text='True if record failed business rules (blank invoice, date mismatch, etc.)'),
        ),
        migrations.AlterField(
            model_name='invoiceproficiency',
            name='invoiced_time_hours',
            field=models.FloatField(default=0.0, help_text='Auto-calculated from items_detail worth time'),
        ),
        migrations.AlterField(
            model_name='invoiceproficiency',
            name='items_detail',
            field=models.JSONField(blank=True, default=list, help_text='Raw item data from scraper (no pre-calculated worth)'),
        ),
        migrations.AlterField(
            model_name='invoiceproficiency',
            name='proficiency_percentage',
            field=models.FloatField(default=0.0, help_text='Auto-calculated: Invoiced Time / Worked Time * 100'),
        ),
        migrations.AlterField(
            model_name='invoiceproficiency',
            name='worked_time_hours',
            field=models.FloatField(default=0.0, help_text='Time worked in decimal hours (raw from scraper)'),
        ),
    ]
