# Generated by Django 5.2.10 on 2026-04-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0004_invoiceproficiency_error_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproficiency',
            name='error_description',
            field=models.TextField(blank=True, help_text='Description of why the record is invalid', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproficiency',
            name='is_invalid',
            field=models.BooleanField(default=False, help_text='Marked as error (e.g. date mismatch > 5 days)'),
        ),
    ]
