# Generated by Django 5.2.10 on 2026-04-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_proficiency', '0005_alter_invoiceproficiency_error_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproficiency',
            name='error_description',
        ),
        migrations.RemoveField(
            model_name='invoiceproficiency',
            name='is_invalid',
        ),
        migrations.AddField(
            model_name='invoiceproficiency',
            name='error_type',
            field=models.CharField(blank=True, help_text='e.g. DATE_MISMATCH, NO_INVOICE_FOUND', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceproficiency',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
